name: Publish Image

on:
  push: # push 到主分支自动 发布
    branches: ["main"]
    paths-ignore: # 忽略一些不必要的文件
      - ".gitignore"
      - "README.md"
      - ".vscode/**"
  pull_request:
    branches: ["main"]
env:
  REGISTRY: registry.cn-hangzhou.aliyuncs.com
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }} # 声明镜像源
          username: ${{ secrets.aliacrname }} # 仓库Action 中的secrets 
          password: ${{ secrets.aliacrpass }} # 仓库Action 中的secrets  
          
      - uses: actions/setup-node@v2
        with:
          node-version: "16.14"  # 指定node版本

      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
        # Runs a single command using the runners shell
      - name: pnpm install
        run: npm install -g pnpm --registry https://registry.npm.taobao.org

      - name: Install
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm config set registry https://registry.npm.taobao.org && pnpm i

      - name: Build
        run: npm run build

      - name: Build the  Docker image
        run:
          | # 使用 上一步写的 Dockerfile 构建镜像并发布到私有仓库； 发布完成可以去 https://github.com/MrGaoGang?tab=packages 查看
          docker build . --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com
          docker push registry.cn-hangzhou.aliyuncs.com


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to dev
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }} # 服务器ip地址 ; 需要去仓库的 settings/secrets/actions 去创建
          username: ${{ secrets.SERVER_USER }} # 服务器用户名称；需要去仓库的 settings/secrets/actions 去创建
          password: ${{ secrets.SERVER_PWD }} # 服务器密码；需要去仓库的 settings/secrets/actions 去创建
          port: ${{ secrets.SERVER_PORT }} # 服务器端口，默认22；需要去仓库的 settings/secrets/actions 去创建
          script: | #login shell 
            docker login -u ${{ secrets.aliacrname }} -p ${{ secrets.aliacrpass }}
            docker pull registry.cn-hangzhou.aliyuncs.com

      - name: Deploy to pre-prod
        if: github.ref == 'refs/heads/staging'
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }} # 服务器ip地址 ; 需要去仓库的 settings/secrets/actions 去创建
          username: ${{ secrets.SERVER_USER }} # 服务器用户名称；需要去仓库的 settings/secrets/actions 去创建
          password: ${{ secrets.SERVER_PWD }} # 服务器密码；需要去仓库的 settings/secrets/actions 去创建
          port: ${{ secrets.SERVER_PORT }} # 服务器端口，默认22；需要去仓库的 settings/secrets/actions 去创建
          script: | #login shell 
            docker login -u ${{ secrets.aliacrname }} -p ${{ secrets.aliacrpass }}
            docker pull registry.cn-hangzhou.aliyuncs.com

      - name: Deploy to prod
        if: github.ref == 'refs/heads/development'
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }} # 服务器ip地址 ; 需要去仓库的 settings/secrets/actions 去创建
          username: ${{ secrets.SERVER_USER }} # 服务器用户名称；需要去仓库的 settings/secrets/actions 去创建
          password: ${{ secrets.SERVER_PWD }} # 服务器密码；需要去仓库的 settings/secrets/actions 去创建
          port: ${{ secrets.SERVER_PORT }} # 服务器端口，默认22；需要去仓库的 settings/secrets/actions 去创建
          script: | #login shell 
            docker login -u ${{ secrets.aliacrname }} -p ${{ secrets.aliacrpass }}
            docker pull registry.cn-hangzhou.aliyuncs.com